package Frames;

import Util.DBConnection;
import Util.PasswordGenerator;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JSlider;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jet
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Edit() {
        initComponents();
    }

    public int currentUserId;
    public int id;
    public String name;
    public String email;
    public String password;
    
    public Main main;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void populateFields(){
        NameTextField.setText(name);
        EmailTextField.setText(email);
        PasswordField.setText(password);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        TextLabel = new javax.swing.JLabel();
        inputLabel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        inputLabel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        inputLabel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        ShowPasswordBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        setSize(new java.awt.Dimension(549, 549));

        MainPanel.setBackground(new java.awt.Color(246, 247, 249));
        MainPanel.setForeground(new java.awt.Color(13, 15, 18));

        titlePanel.setBackground(new java.awt.Color(246, 247, 249));
        titlePanel.setLayout(new java.awt.BorderLayout(0, 10));

        TextLabel.setFont(TextLabel.getFont().deriveFont(TextLabel.getFont().getSize()+11f));
        TextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextLabel.setText("Edit Credentials");
        titlePanel.add(TextLabel, java.awt.BorderLayout.PAGE_END);

        inputLabel.setBackground(new java.awt.Color(246, 247, 249));
        inputLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));
        inputLabel.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+1f));
        jLabel3.setText("Email Address");
        inputLabel.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        EmailTextField.setBackground(new java.awt.Color(216, 221, 228));
        EmailTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        EmailTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        EmailTextField.setMargin(new java.awt.Insets(2, 10, 2, 6));
        EmailTextField.setPreferredSize(new java.awt.Dimension(78, 38));
        EmailTextField.setSize(new java.awt.Dimension(78, 38));
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });
        inputLabel.add(EmailTextField, java.awt.BorderLayout.PAGE_END);

        inputLabel1.setBackground(new java.awt.Color(246, 247, 249));
        inputLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        inputLabel1.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()+1f));
        jLabel4.setText("Password");
        inputLabel1.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        PasswordField.setBackground(new java.awt.Color(216, 221, 228));
        PasswordField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        PasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        PasswordField.setPreferredSize(new java.awt.Dimension(90, 38));
        inputLabel1.add(PasswordField, java.awt.BorderLayout.CENTER);

        inputLabel5.setBackground(new java.awt.Color(246, 247, 249));
        inputLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));
        inputLabel5.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()+1f));
        jLabel5.setText("Name");
        inputLabel5.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        NameTextField.setBackground(new java.awt.Color(216, 221, 228));
        NameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        NameTextField.setMargin(new java.awt.Insets(2, 10, 2, 6));
        NameTextField.setPreferredSize(new java.awt.Dimension(78, 38));
        NameTextField.setSize(new java.awt.Dimension(78, 38));
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });
        inputLabel5.add(NameTextField, java.awt.BorderLayout.PAGE_END);

        cancelBtn.setBackground(new java.awt.Color(56, 68, 81));
        cancelBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelBtn.setPreferredSize(new java.awt.Dimension(78, 38));
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        SaveBtn.setBackground(new java.awt.Color(56, 68, 81));
        SaveBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        SaveBtn.setText("Update");
        SaveBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SaveBtn.setPreferredSize(new java.awt.Dimension(78, 38));
        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        ShowPasswordBtn.setBackground(new java.awt.Color(56, 68, 81));
        ShowPasswordBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShowPasswordBtn.setForeground(new java.awt.Color(255, 255, 255));
        ShowPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-view-30.png"))); // NOI18N
        ShowPasswordBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ShowPasswordBtn.setPreferredSize(new java.awt.Dimension(78, 38));
        ShowPasswordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPasswordBtnMouseClicked(evt);
            }
        });
        ShowPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titlePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
            .addComponent(inputLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(inputLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShowPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ShowPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowPasswordBtnActionPerformed

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBtnMouseClicked
        // TODO add your handling code here:
        try {
            Connection con = (new DBConnection()).getConnection();
            
            String name = NameTextField.getText();
            if(name.isBlank()){
                JOptionPane.showMessageDialog(rootPane, "Name cannot be empty");
                return;
            }
            // Search for existing emails
            String email = EmailTextField.getText();
            if(email.isBlank()){
                JOptionPane.showMessageDialog(rootPane, "Email cannot be empty");
                return;
            }
            
            String password = new String(PasswordField.getPassword());
            if(name.isBlank()){
                JOptionPane.showMessageDialog(rootPane, "Password cannot be empty");
                return;
            }
            
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("SELECT * FROM users WHERE id = ?");
            ps.setInt(1, currentUserId);
            ResultSet rs = ps.executeQuery();
            
            if(!rs.next()){
                // Current user is not found
                System.err.println("Found");
                JOptionPane.showMessageDialog(rootPane, "User doesn't exists, Please re login");
                Login login = new Login();
                login.setVisible(true);
                dispose();

            } else {
                // continue
                ps = (PreparedStatement) con.prepareStatement("UPDATE `credentials` SET `name` = ?, `email` = ?, `password` = ? WHERE id = ?");
                ps.setString(1, name);
                ps.setString(2, email);
                ps.setString(3, password);
                ps.setInt(4, id);

                
                ps.execute();
                System.out.println("Credential Saved");
                // TODO: Refresh table on main
                main.refreshTable();
                dispose();
            }
            
          
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_SaveBtnMouseClicked

    private void ShowPasswordBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPasswordBtnMouseClicked
        // TODO add your handling code here:
        if(PasswordField.echoCharIsSet()){
            PasswordField.setEchoChar((char) 0);
        } else {
            PasswordField.setEchoChar('*');
        }
        
    }//GEN-LAST:event_ShowPasswordBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton ShowPasswordBtn;
    private javax.swing.JLabel TextLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel inputLabel;
    private javax.swing.JPanel inputLabel1;
    private javax.swing.JPanel inputLabel5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
